services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_CLOUD_PROJECT: datahub-478802
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
      - ./app/credentials:/app/credentials

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    restart: always
    ports:
      - "8501:8501"
    command: python -m streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    depends_on:
      - app
    volumes:
      - ./app:/app
    environment:
      - API_URL=http://app:8000

  server:
      image: redash/redash:10.1.0.b50633
      command: server
      depends_on:
        - postgres
        - redis
      ports:
        - "5000:5000"
      env_file: .env
      restart: always

  scheduler:
    image: redash/redash:10.1.0.b50633
    command: scheduler
    depends_on:
      - server
    env_file: .env
    restart: always

  scheduled_worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    depends_on:
      - server
    env_file: .env
    restart: always

  adhoc_worker:
    image: redash/redash:10.1.0.b50633
    command: worker
    depends_on:
      - server
    env_file: .env
    restart: always

  # 데이터 저장소 (PostgreSQL)
  postgres:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always

  # 메시지 브로커 및 캐시 (Redis)
  redis:
    image: redis:6-alpine
    restart: always

volumes:
  mysql_data: